@startuml
'https://plantuml.com/class-diagram


database MySQL{
    entity User {
        id : String
        ---
        name : String
        userId : String
        userPw : String
        phoneNumber : String
        custStatus : String
        createdAt : LocalDateTime
        updatedAt : LocalDateTime
    }

    entity Group {
        id : String
        ---
        name : String
        description : String
        createdAt : LocalDateTime
        updatedAt : LocalDateTime
    }

    entity Coupon {
        id : String
        ---
        imagePath : String
        status : boolean
        createdBy : String
        createdAt : LocalDateTime
        owner : String
        updatedBy : String
        updatedAt : LocalDateTime
        ---
        (company) : String
        (menuName) : String
        (amount) : Long
        (barcode) : String
        (dueDate) : LocalDateTime
    }

    entity CouponHistory {
        id : String
        ---
        couponId : String
        imagePath : String
        status : boolean
        owner : String
        createdBy : String
        createdAt : LocalDateTime
        ---
        (company) : String
        (menuName) : String
        (amount) : Long
        (barcode) : String
        (dueDate) : LocalDateTime
    }

    entity UserAndGroup {
        id : String
        userId : String
        groupId : String
    }

    entity GroupAndCoupon {
        id : String
        groupId : String
        couponId : String
    }
}

Group ||--o{ GroupAndCoupon : id = groupId
Coupon ||--o{ GroupAndCoupon : id = couponId
User ||--o{ UserAndGroup : id = userId
Group ||--o{ UserAndGroup : id = groupId

Coupon ||--|{ CouponHistory : id = couponId


@enduml
